// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewsSite;

namespace ReviewsSite.Migrations
{
    [DbContext(typeof(ParkContext))]
    partial class ParkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReviewsSite.Models.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasHandicapAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDogFriendly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasHandicapAccess = true,
                            IsDogFriendly = true,
                            Name = "Edgewater",
                            ParkDescription = "The 147 acre Edgewater Park is the westernmost park in Cleveland Metroparks Lakefront Reservation. Edgewater Park features 9000 feet of shoreline, beaches, boat ramps,  fishing pier, picnic areas and grills. The park is both wheelchair accessible and dog friendly. Open daily 6am to 11pm. Located at 6500 Cleveland Memorial Shoreway in Cleveland",
                            ParkType = "Beach"
                        },
                        new
                        {
                            Id = 2,
                            HasHandicapAccess = false,
                            IsDogFriendly = true,
                            Name = "Mohican",
                            ParkDescription = "Has thousands of acres covered in woods and offers many hiking trails and water features. There is also a full-service lodge and family campground with a pool. Hours of operation vary depending on area and is located at 3116 OH-3 in Loudonville,Ohio.",
                            ParkType = "River"
                        },
                        new
                        {
                            Id = 3,
                            HasHandicapAccess = false,
                            IsDogFriendly = false,
                            Name = "Kurtz",
                            ParkDescription = "Kurtz  park in Cuyahoga County has an elevation of 856 feet and is situated west of Parma Heights, located near Brook Park Fire Department Station 4.",
                            ParkType = "Sport"
                        });
                });

            modelBuilder.Entity("ReviewsSite.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "I really like take my dog to poop here.",
                            ParkId = 1,
                            ReviewerName = "Crys",
                            StarRating = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "This place is great, I love to canoe!!",
                            ParkId = 2,
                            ReviewerName = "Richard",
                            StarRating = 5
                        },
                        new
                        {
                            Id = 3,
                            Comment = "The park is nice.",
                            ParkId = 3,
                            ReviewerName = "Kayley",
                            StarRating = 3
                        });
                });

            modelBuilder.Entity("ReviewsSite.Models.Review", b =>
                {
                    b.HasOne("ReviewsSite.Models.Park", "Park")
                        .WithMany("Reviews")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("ReviewsSite.Models.Park", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
